# Generated by Django 5.0.3 on 2024-04-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('current_population', models.IntegerField()),
                ('demographic_info', models.JSONField()),
                ('shelter_type', models.CharField(max_length=100)),
                ('economic_activities', models.TextField()),
                ('health_education_info', models.JSONField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('IDP', 'IDP'), ('Host', 'Host'), ('Volunteer', 'Volunteer'), ('NDRMC Admin', 'NDRMC Admin'), ('Camp Admin', 'Camp Admin'), ('NGO', 'NGO')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('preference', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('hosting_experience', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('legal_doc_id', models.CharField(max_length=100)),
                ('economic_status', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_origin', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('household_composition', models.IntegerField()),
                ('vulnerability_status', models.CharField(max_length=100)),
                ('health_status', models.CharField(max_length=100)),
                ('documentation_status', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('language_spoken', models.CharField(max_length=100)),
                ('previous_assistance_received', models.CharField(max_length=100)),
                ('protection_concerns', models.CharField(max_length=100)),
                ('economic_status', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IdpCampAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IdpVolunteerAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idp_volunteer_associations', to='app.actorprofile')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_associations', to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app.actorprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('legal_doc', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IdpNGOAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ActorProfileResourceAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceIdpAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateTimeField(auto_now_add=True)),
                ('quantity_used', models.IntegerField()),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField()),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='app.actorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actorprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPhotoAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.photo')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
        ),
    ]
