# Generated by Django 5.0.3 on 2024-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_idppre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='household_composition',
            field=models.CharField(max_length=100),
        ),
    ]
