# Generated by Django 5.0.3 on 2024-05-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.AddField(
            model_name='photo',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.story'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StoryPhotoAssociation',
        ),
    ]
